services:
  sdk:
    image: openwrt/sdk:mips_24kc
    volumes:
      - .:/builder/local-build/natmap
      - ./bin:/builder/bin
      - ./build.sh:/builder/build.sh
      - ./key-build:/builder/key-build
    command: /builder/build.sh
      